#!/bin/sh

# BDADDR=$(cat `getprop ro.bt.bdaddr_path`)
PATCHRAM_ARGS="--patchram /vendor/firmware/bcm4358A1_V0054.0095.hcd \
               --enable_hci \
               --enable_lpm \
               --no2bytes \
               --tosleep 1000 \
               --baudrate 3000000 --use_baudrate_for_download"
#               --scopcm=0,4,0,0,0,0,0,3,0,0 \
#               --bd_addr $BDADDR"

chmod 0660 /sys/class/rfkill/rfkill0/state
chmod 0660 /sys/class/rfkill/rfkill0/type
chgrp dialout /sys/class/rfkill/rfkill0/state
chgrp dialout /sys/class/rfkill/rfkill0/type
rfkill unblock bluetooth

/usr/bin/brcm_patchram_plus $PATCHRAM_ARGS /dev/ttyHS0 &

